---
training_filename: data/a1a
testing_filename: data/a1a.t
num_examples: 1605
num_testing_examples: 30956
num_features: 125
positive: +1
max_sample_size: 20000
max_bin_size: 10
min_gamma: 0.00001
default_gamma: 0.25
max_trials_before_shrink: 20000
min_ess: 0.5
model_length: 15
max_leaves: 2
channel_size: 128
buffer_size: 20000
batch_size: 1000
serial_sampling: false
num_examples_per_block: 128
disk_buffer_filename: stratified.bin
num_assigners: 2
num_samplers: 2
debug_mode: false